# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
pool:
  vmImage: 'macos-latest'
steps:
- task: UseNode@1
  inputs:
    version: '12.x'
  displayName: 'Use Node 12.x'
- script: |
    npm install -g ionic cordova
  displayName: 'Install ionic & cordova tools'
- script: |
    export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
    export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
    export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
    export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
    export PATH=$PATH:$ANDROID_SDK_ROOT/build-tools
  displayName: 'Export environment variables'
- script: |
    npm ci
  displayName: 'Install dependencies'
- task: DownloadSecureFile@1
  name: googleServices
  displayName: 'Download google-services.json'
  inputs:
    secureFile: 'google-services.json'
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    contents: google-services.json
    targetFolder: $(Build.SourcesDirectory)
- script: |
    ionic cordova build android
  displayName: "Run build android"
# - script: |
#     npm run lint --if-present
#   displayName: 'Run linting'
# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'android'
#     targetPath: 'platforms/android'
#   displayName: 'Publish build android artifacts'
# - task: Gradle@2
#   inputs:
#     workingDirectory: ''
#     gradleWrapperFile: 'gradlew'
#     gradleOptions: '-Xmx3072m'
#     publishJUnitResults: false
#     testResultsFiles: '**/TEST-*.xml'
#     tasks: 'assembleDebug'
