name: Main Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build and lint
      run: |
        npm ci
        npm run build --if-present
        npm run lint --if-present
      env:
        CI: true
